# Generated by Django 3.1.4 on 2021-01-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakistan',
            old_name='name_3',
            new_name='name',
        ),
    ]
