# Generated by Django 3.1.4 on 2021-01-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0002_auto_20210104_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakistan',
            name='selected_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pakistan',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
