# Generated by Django 3.1.4 on 2021-01-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0003_auto_20210102_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakistan',
            name='engtype_3',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='nl_name_3',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='type_3',
        ),
        migrations.RemoveField(
            model_name='pakistan',
            name='varname_3',
        ),
    ]
