# Generated by Django 3.1.4 on 2021-01-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0004_auto_20210102_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakistan',
            old_name='name_3',
            new_name='name',
        ),
    ]
