# Generated by Django 3.1.4 on 2021-01-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0005_auto_20210102_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape_app.pakistan')),
            ],
        ),
    ]
