# Generated by Django 3.1.4 on 2021-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0006_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
