# Generated by Django 3.1.4 on 2021-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0007_auto_20210102_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakistan',
            name='selection_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
