# Generated by Django 3.1.4 on 2021-01-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0008_pakistan_selection_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakistan',
            old_name='selection_color',
            new_name='selected_color',
        ),
    ]
