# Generated by Django 3.1.4 on 2021-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0009_auto_20210103_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='area',
        ),
        migrations.AddField(
            model_name='areas',
            name='area',
            field=models.ManyToManyField(to='shape_app.Pakistan'),
        ),
    ]
