# Generated by Django 3.1.4 on 2021-01-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_app', '0010_auto_20210104_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='shape_app.Pakistan'),
        ),
    ]
